Models/CalcModel.cs
namespace Calculator.Models
{
    public class Calc{
        public int no1{get;set;}

        public int no2{get;set;}

        public int tot{get;set;}


    }
}

Models/ErrorViewModel.cs
namespace Calculator.Models;

public class ErrorViewModel
{
    public string? RequestId { get; set; }

    public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
}

Controllers/CalcController.cs
using System.Diagnostics;
using Microsoft.AspNetCore.Mvc;
using Calculator.Models;

namespace Calculator.Controllers;

public class CalcController : Controller
{
    public ActionResult Index()
    {
        return View(new Calc());
    }

    [HttpPost]
    public ActionResult Index(Calc c,string calculate)
    {
        if(calculate == "add")
        {
            c.tot = c.no1 + c.no2;
        } else if(calculate == "min")
        {
            c.tot = c.no1 - c.no2;
        } else if(calculate == "sub")
        {
            c.tot = c.no1 * c.no2;
        } else if(calculate == "div")
        {
            c.tot = c.no1 / c.no2;
        }

        return View(c);
    }
}

Controllers/HomeController.cs
using System.Diagnostics;
using Microsoft.AspNetCore.Mvc;
using Calculator.Models;

namespace Calculator.Controllers;

public class HomeController : Controller
{
    private readonly ILogger<HomeController> _logger;

    public HomeController(ILogger<HomeController> logger)
    {
        _logger = logger;
    }

    public IActionResult Index()
    {
        return View();
    }

    public IActionResult Privacy()
    {
        return View();
    }

    [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
    public IActionResult Error()
    {
        return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
    }
}

Views/Calc/Index.cshtml
@model Calculator.Models.Calc
@{
    ViewBag.Title = "Index";
}

<html>
    <head>
        <body>
            <h1>Simple Calculator</h1>

            <div class = "row">
                @using (Html.BeginForm("Index","Calc", FormMethod.Post))
                {
                    <div class = "form-group">
                        <label for="no1">No 1</label>
                        <input type = "text" class ="form-control" id="no1" name = "no1" value="@Model.no1"/>
                    </div>

                    <div class = "form-group">
                        <label for="no2">No 2</label>
                        <input type = "text" class ="form-control" id="no2" name = "no2" value="@Model.no2"/>
                    </div>

                    <div class = "form-group">
                        <label for="total">No 1</label>
                        <input type = "text" class ="form-control" id="tot" name = "tot" value="@Model.tot"/>
                    </div>

                    <button type = "submit" class = "btn btn-info" id="add" value="add" name = "calculate">+</button>

                    <button type = "submit" class = "btn btn-info" id="min" value="min" name = "calculate">-</button>

                    <button type = "submit" class = "btn btn-info" id="sub" value="sub" name = "calculate">*</button>

                    <button type = "submit" class = "btn btn-info" id="div" value="div" name = "calculate">/</button>
                }

            </div>







        </body>





    </head>



</html>

Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Calculator</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/Calculator.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Calculator</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Calc" asp-action="Index">Calculator</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2022 - Calculator - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>